---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"
nginx_extras_package: "nginx-extras"

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"
nginx_security_template: "security.conf.j2"

nginx_worker_processes: "1"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

# leave TLS 1 and SSL2/3 disabled
nginx_ssl_protocols: "TLSv1.2 TLSv1.1"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

api_nginx_error_log: "/var/log/nginx/api-error.log warn"
api_nginx_access_log: "/var/log/nginx/api-access.log main buffer=16k flush=2m"

web_nginx_error_log: "/var/log/nginx/web-error.log warn"
web_nginx_access_log: "/var/log/nginx/web-access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_server_tokens: "off"
nginx_server_tokens_show_custom: "true"
nginx_server_tokens_custom_headers: "OMSCS Discussions"

nginx_client_max_body_size: "1k"
nginx_client_body_buffer_size: "1K"
nginx_client_header_buffer_size: "1k"
nginx_large_client_header_buffers: "2 1k"

nginx_client_body_timeout: "10"
nginx_client_header_timeout: "10"
nginx_keepalive_timeout: "5 5"
nginx_send_timeout: "10"

nginx_gzip_types: "text/plain text/css text/xml application/xml application/xml+rss image/svg+xml application/json application/javascript application/x-javascript text/javascript"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: true
nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80" # default: "80"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#   filename: "example.com.conf" # Can be used to set the filename of the vhost file.
#
#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#   state: "absent" # To remove the vhost configuration.

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
