---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'


# Vhost configuration.
- import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Copy security configuration in place.
  template: 
    src: "{{ nginx_security_template }}"
    dest: "{{ nginx_conf_security_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes

- name: Create symlink for frontend
  file:
    src: '{{ nginx_sites_available }}/default'
    dest: '{{ nginx_default_vhost_path }}/default'
    state: link
  notify:
    - reload nginx
    
- name: Create symlink for api
  file:
    src: '{{ nginx_sites_available }}/api'
    dest: '{{ nginx_default_vhost_path }}/api'
    state: link
  notify:
    - reload nginx
    