---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx_package_name }}"
    state: present
    default_release: "{{ nginx_default_release }}"

- name: Install nginx extras.
  apt:
    name: "{{ nginx_extras_package }}"
    state: present 
